# Generated by Django 3.1.1 on 2020-10-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Значение', 'verbose_name_plural': 'Значения'},
        ),
    ]
