"""Создали новую таблицу

Revision ID: 0c6deba78a42
Revises: fb2ab04df60c
Create Date: 2021-04-20 12:19:54.728402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6deba78a42'
down_revision = 'fb2ab04df60c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_column('users', 'order_message')
    op.drop_column('users', 'forwarding_mail_adress')
    op.drop_column('users', 'delivery_mail_adress')
    op.drop_column('users', 'random_order_code')
    op.drop_column('users', 'delivery_city')
    op.drop_column('users', 'forwarding_city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('forwarding_city', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('delivery_city', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('random_order_code', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('delivery_mail_adress', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('forwarding_mail_adress', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('order_message', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
