"""Подкорректировали таблицу user

Revision ID: 4045a9068928
Revises: 9d15aecb8c7f
Create Date: 2021-04-21 16:51:44.529217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4045a9068928'
down_revision = '9d15aecb8c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'delivery_and_orders', ['random_order_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery_and_orders', type_='unique')
    # ### end Alembic commands ###
