"""добавили новые поля для заказов

Revision ID: 4178b87e7641
Revises: 
Create Date: 2021-04-19 21:44:25.037130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4178b87e7641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('forwarding_city', sa.String(), nullable=False),
    sa.Column('delivery_city', sa.String(), nullable=False),
    sa.Column('order_message', sa.String(), nullable=False),
    sa.Column('forwarding_mail_adress', sa.String(), nullable=False),
    sa.Column('delivery_mail_adress', sa.String(), nullable=False),
    sa.Column('random_order_code', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
