"""Подкорректировали таблицу use r

Revision ID: 87e7f633bdea
Revises: 4045a9068928
Create Date: 2021-04-21 18:43:25.294219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e7f633bdea'
down_revision = '4045a9068928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_and_orders', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'delivery_and_orders', ['random_order_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery_and_orders', type_='unique')
    op.drop_column('delivery_and_orders', 'email')
    # ### end Alembic commands ###
