"""Добавили поле с email

Revision ID: 9d15aecb8c7f
Revises: bdb9d0f0c05f
Create Date: 2021-04-20 17:11:07.045081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d15aecb8c7f'
down_revision = 'bdb9d0f0c05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_and_orders', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'delivery_and_orders', ['random_order_code'])
    op.drop_column('users', 'delivery_city')
    op.drop_column('users', 'forwarding_city')
    op.drop_column('users', 'forwarding_mail_adress')
    op.drop_column('users', 'delivery_mail_adress')
    op.drop_column('users', 'order_message')
    op.drop_column('users', 'username')
    op.drop_column('users', 'random_order_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('random_order_code', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('order_message', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('delivery_mail_adress', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('forwarding_mail_adress', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('forwarding_city', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('delivery_city', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'delivery_and_orders', type_='unique')
    op.drop_column('delivery_and_orders', 'email')
    # ### end Alembic commands ###
