"""Обновили значения

Revision ID: fb2ab04df60c
Revises: 4178b87e7641
Create Date: 2021-04-20 12:01:48.651416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2ab04df60c'
down_revision = '4178b87e7641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'delivery_city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'delivery_mail_adress',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'forwarding_city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'forwarding_mail_adress',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'order_message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'random_order_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'random_order_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'order_message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'forwarding_mail_adress',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'forwarding_city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'delivery_mail_adress',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'delivery_city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
